# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
   #fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally set the version of Python and requirements required to build your docs
# -- little hack to get vext installed before installing vext.gi
python:
   version: 3.9
   install:
   - requirements: docs/requirements.txt
   - requirements: docs/requirements-rtd.txt

build:
  image: testing
  apt_packages:
    - libgirepository1.0-dev
    - gir1.2-atspi-2.0
    - python3-gi
